### ISSUE TITLE
SongPress doesn't launch on Ubuntu 22.04

### ISSUE THREAD

**Issue by CodeShakingSheep** [lallulli/songpress#62]
OS: Ubuntu 22.04
Python version: 3.10.12
wxPython version: 4.0.7

This is the error report:

```
#---- Notes ----#
Please provide additional information about the crash here


#---- System Information ----#
Songpress Version: 1.8.1
Operating System: Linux 6.8.0-65-generic x86_64
Python Version: 3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0]
wxPython Version: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5
wxPython Info: (__WXGTK__, wxGTK, unicode, unicode-wchar, gtk3, wx-assertions-on, phoenix, wxWidgets 3.0.5, sip-6.5.1, build-type: development)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 64bit x86_64
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Mon Aug  4 17:37:32 2025 ***
Traceback (most recent call last):
  File "/home/uh/Downloads/songpress-1.8.1/src/main.py", line 32, in OnInit
    songpressFrame = SongpressFrame.SongpressFrame(self.res)
  File "/home/uh/Downloads/songpress-1.8.1/src/SongpressFrame.py", line 210, in __init__
    self.pref = Preferences()
  File "/home/uh/Downloads/songpress-1.8.1/src/Preferences.py", line 57, in __init__
    self.format = SongFormat()
  File "/home/uh/Downloads/songpress-1.8.1/src/SongFormat.py", line 89, in __init__
    ParagraphFormat.__init__(self, ff)
  File "/home/uh/Downloads/songpress-1.8.1/src/SongFormat.py", line 81, in __init__
    self.chord.size = self.size * 0.9
  File "/home/uh/Downloads/songpress-1.8.1/src/SongFormat.py", line 25, in __setattr__
    h.OnSetAttr(self, name, value)
  File "/home/uh/Downloads/songpress-1.8.1/src/SongFormat.py", line 35, in OnSetAttr
    format.UpdateWxFont()
  File "/home/uh/Downloads/songpress-1.8.1/src/SongFormat.py", line 67, in UpdateWxFont
    self.wxFont = wx.Font(self.size, wx.FONTFAMILY_DEFAULT, style, weight, self.underline, self.face)
TypeError: Font(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'float'

#---- End Traceback Info ----#
```

Grateful for any hints about how to fix this 🙏

**Comment by lallulli** [comment]
Thanks for the report! This specific bug (caused by stricter requirements for parameter types in newer wxPython versions) had already been fixed in master. I have fixed a similar bug today. You can download the latest version from the repository, it should work.

In the near future I would like to simplify and standardize installation on Linux (and Windows), by relying on PyPI and pipx.

**Comment by CodeShakingSheep** [comment]
Thanks for the reply @lallulli . I just pulled the latest version from master. When I launch it from `src` folder with `python3 main.py` I'm still getting an error which is slightly different than the previous one (different traceback).

```
#---- Notes ----#
Please provide additional information about the crash here


#---- System Information ----#
Songpress Version: 1.9.0
Operating System: Linux 6.8.0-65-generic x86_64
Python Version: 3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0]
wxPython Version: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5
wxPython Info: (__WXGTK__, wxGTK, unicode, unicode-wchar, gtk3, wx-assertions-on, phoenix, wxWidgets 3.0.5, sip-6.5.1, build-type: development)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 64bit x86_64
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Wed Aug 20 19:04:43 2025 ***
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibar.py", line 3510, in OnPaint
    self._art.DrawButton(dc, self, item, item_rect)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibar.py", line 1008, in DrawButton
    bmp_rect, text_rect = self.GetToolsPosition(dc, item, rect)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibar.py", line 1508, in GetToolsPosition
    bmp_rect = wx.Rect(bmp_x, bmp_y, bmp_width, bmp_height)
TypeError: Rect(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'

#---- End Traceback Info ----#
```

**Comment by CodeShakingSheep** [comment]
I managed to update `wxPython` on my system with prebuilt wheel `pip install -U --pre -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04`.

Now SongPress launches normally 🚀
